# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: c

before_install:
  - sudo apt-get install gccxml doxygen libclang-dev
  - git clone https://github.com/trolldbois/python-clang && cd python-clang && sudo python setup.py install && cd ..
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_deps

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
